# Generated by Django 5.1 on 2024-09-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_playedtrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedtrack',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
