# Generated by Django 5.1.1 on 2024-09-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_playedtrack_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playedtrack',
            name='cover',
        ),
    ]
